apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: erdc-poc-http-vs
  namespace: frontend-public
spec:
  hosts:
  - "poc.powerdreams.app"
  gateways:
  - aks-istio-ingress/erdc-poc-internal-gateway
  http:
  - match:
    - uri:
        prefix: "/internal"
    rewrite:
      uri: "/"
    route:
    - destination:
        host: erdc-poc-svc-be.frontend-private.svc.cluster.local
        port:
          number: 80
  - match:
    - uri:
        prefix: "/"
    route:
    - destination:
        host: erdc-poc-svc.frontend-public.svc.cluster.local
        port:
          number: 80
